export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAILED = 'VALIDATE_TOKEN_FAILED';

export const LOGOUT = 'LOGOUT';

export const GET_ACTION_BY_ID = 'GET_ACTION_BY_ID';
export const GET_ACTION_BY_ID_SUCCESS = 'GET_ACTION_BY_ID_SUCCESS';
export const GET_ACTION_BY_ID_FAILED = 'GET_ACTION_BY_ID_FAILED';

export const GET_ACTION_LIST = 'GET_ACTION_LIST';
export const GET_ACTION_LIST_SUCCESS = 'GET_ACTION_LIST_SUCCESS';
export const GET_ACTION_LIST_FAILED = 'GET_ACTION_LIST_FAILED';

export const DELETE_ACTION = 'DELETE_ACTION';
export const DELETE_ACTION_SUCCESS = 'DELETE_ACTION_SUCCESS';
export const DELETE_ACTION_FAILED = 'DELETE_ACTION_FAILED';

export const CREATE_ACTION = 'CREATE_ACTION';
export const CREATE_ACTION_SUCCESS = 'CREATE_ACTION_SUCCESS';
export const CREATE_ACTION_FAILED = 'CREATE_ACTION_FAILED';

export const UPDATE_ACTION = 'UDATE_ACTION';
export const UPDATE_ACTION_SUCCESS = 'UDATE_ACTION_SUCCESS';
export const UPDATE_ACTION_FAILED = 'UDATE_ACTION_FAILED';
